# Generated by Django 2.0 on 2019-09-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')])),
                ('upload', models.FileField(upload_to='uploads/')),
                ('image', models.ImageField(help_text='只能上传图片', upload_to='')),
                ('email_filed', models.EmailField(default='test@test.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RedisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_type', models.CharField(max_length=5, unique=True)),
                ('redis_type', models.IntegerField(choices=[(0, '哨兵'), (1, '集群')])),
                ('redis_port', models.IntegerField(default=6379, verbose_name='Redis 端口')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('host_ip', models.CharField(default='请输入ip', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
