# Generated by Django 2.0 on 2019-10-01 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_fileupload_nginxacess_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 7, 47, 21, 997658, tzinfo=utc)),
        ),
    ]
