# Generated by Django 2.0 on 2019-10-01 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191001_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 8, 8, 37, 377955, tzinfo=utc)),
        ),
    ]
